### ISSUE TITLE
Getting 403 error while using quickstart guide 

### ISSUE THREAD

**Issue by nalangekrushna** [acrolinx/platform-api#116]
Steps to reproduce

1. download the collection file from [this] (https://github.com/acrolinx/platform-api/blob/main/quickstart.md) page.
2. create new environment in postman using below variables.
    - ACROLINX_URL: dev environment url of our company instance.
    - ACCESS_TOKEN: my own access token generated from user settings.
    - SIGNATURE: copy pasted as it is from quickstart page as we are not certied yet. Let me know if there is any other way to get signature for testing purpose.
    - base64_username_password, user_id, role_id : copy pasted from same page mentioned in above link.
   3. Ran minimal check request ({{ACROLINX_URL}}/api/v1/checking/checks) got 403

we do have dev and prod environment of acrolinx with us which I can login from browser. Let me know if there is any other way to get signature for testing purpose as default signature provided here https://github.com/acrolinx/platform-api is not working for development purpose also.

**Comment by pcdeshmukh** [comment]
Hi @nalangekrushna,

You can't use test signature against your instance. It only works with test instance Acrolinx will provide. Client signature represents an integration and integration needs to get certified first. 

Please follow [steps](https://docs.acrolinx.com/customintegrations/steps-for-building-an-integration) and reach out to your customer success manager to kick start the process.

Thanks,
Paresh
