### ISSUE TITLE
The Postman collection does not import 

### ISSUE THREAD

**Issue by dividor** [acrolinx/platform-api#3]
The Postman collection ...

https://github.com/acrolinx/platform-api/blob/master/Acrolinx-API.postman_collection.json

...  doesn't import to Postman, gives the error "Error while importing: Format not recognized".

I am on Postman version v7.3.4.

Thanks.

**Comment by robertgrabowski** [comment]
I was able to import the collection without problem into Postman v7.3.4.

If you choose "import from link", make sure to use the URL of the raw JSON file: https://raw.githubusercontent.com/acrolinx/platform-api/master/Acrolinx-API.postman_collection.json

Downloading the JSON file and importing it also worked fine for me.

**Comment by dividor** [comment]
Worked perfectly, thanks a lot!
